version: '3.8'

services:
  app:
    build: ./server
    container_name: dropshipping-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - REPORT_RECIPIENT=${REPORT_RECIPIENT}
      - ERROR_RECIPIENT=${ERROR_RECIPIENT}
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - dropshipping-net
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: dropshipping-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - dropshipping-net

  frontend:
    build: ./frontend
    container_name: dropshipping-frontend
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - dropshipping-net
    depends_on:
      - app

volumes:
  redis_data:

networks:
  dropshipping-net:
    driver: bridge
